In [6]:
import numpy as np
import cv2

# Theoretical Explanation of Saturation (S) Calculation
# ------------------------------------------------------
#
# The image processing task involves converting an RGB image to the HSV color model
# and manually calculating the Saturation (S) channel based on RGB components.
#
# In the HSV color space:
#   - **Hue (H)** represents the color type, e.g., Red, Green, Blue, etc.
#   - **Saturation (S)** represents the intensity or purity of the color.
#   - **Value (V)** represents the brightness of the color.
#
# Saturation (S) is an important component that measures the color intensity.
# High saturation values correspond to more vivid colors, whereas low saturation
# values correspond to washed-out or grayscale colors.
#
# The formula used to calculate Saturation (S) manually:
#   - Δ (delta) = C_max - C_min
#       - **C_max** is the maximum value among the Red (R), Green (G), and Blue (B) components.
#       - **C_min** is the minimum value among the Red (R), Green (G), and Blue (B) components.
#   - **Saturation (S)** is calculated as:
#       - **S = Δ / C_max** (if C_max > 0)
#       - **S = 0** (if C_max = 0, i.e., for grayscale colors)
#
# In the case of grayscale colors (where R = G = B), the saturation (S) is defined as 0 because there is no color intensity.
# 
# The manual calculation involves finding the maximum and minimum values of the R, G, and B components for each pixel,
# calculating the difference Δ (delta), and dividing it by the maximum value C_max to get the saturation value.
#
# The result is then scaled to the range [0, 255] to match OpenCV's representation of Saturation (S).
#
# Finally, we compare the Saturation (S) values calculated manually with the ones extracted from OpenCV's HSV conversion
# to verify correctness.

# Define the 3x3 RGB image
image = np.array([
    [[255, 0, 0], [0, 255, 0], [0, 0, 255]],       # Row 1: Red, Green, Blue
    [[255, 255, 0], [0, 255, 255], [255, 0, 255]], # Row 2: Yellow, Cyan, Magenta
    [[128, 128, 128], [64, 64, 64], [32, 32, 32]]  # Row 3: Shades of gray
], dtype=np.uint8)

# Convert to HSV using OpenCV
hsv_image = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)

# Extract Hue (H), Saturation (S), and Value (V) channels from OpenCV
H_channel_opencv = hsv_image[:, :, 0]
S_channel_opencv = hsv_image[:, :, 1]
V_channel_opencv = hsv_image[:, :, 2]

# Manual calculation of Saturation (S)
R, G, B = image[:, :, 0], image[:, :, 1], image[:, :, 2]
C_max = np.max(image, axis=2)
C_min = np.min(image, axis=2)
delta = C_max - C_min

# Saturation formula: S = Δ / C_max
S_channel_manual = np.zeros_like(C_max, dtype=np.float32)

# When C_max > 0, S = Δ / C_max
mask = C_max > 0
S_channel_manual[mask] = delta[mask] / C_max[mask]

# When C_max = 0 (gray pixels), S = 0
S_channel_manual[C_max == 0] = 0

# Scale S to OpenCV range [0, 255]
S_channel_manual = (S_channel_manual * 255).astype(np.uint8)

# Compare results
print("Saturation (S) from OpenCV:")
print(S_channel_opencv)

print("\nManually Calculated Saturation (S):")
print(S_channel_manual)


Saturation (S) from OpenCV:
[[255 255 255]
 [255 255 255]
 [  0   0   0]]

Manually Calculated Saturation (S):
[[255 255 255]
 [255 255 255]
 [  0   0   0]]
