In [1]:
import numpy as np

def gaussian_filter(size, sigma=None):
    """
    Generates a Gaussian filter (kernel) with specified size and standard deviation (sigma).
    
    Parameters:
    - size (int): The size of the filter (e.g., 3 for 3x3, 5 for 5x5, etc.). Must be an odd number.
    - sigma (float): The standard deviation of the Gaussian function. If None, it defaults to size / 6.
    
    Returns:
    - kernel (numpy.ndarray): A normalized 2D Gaussian filter of the specified size.
    """
    # Ensure the filter size is an odd number
    if size % 2 == 0:
        raise ValueError("Filter size must be an odd number.")
    
    # Set sigma based on size if not provided
    if sigma is None:
        sigma = size / 6.0
    
    # Initialize the filter
    kernel = np.zeros((size, size), dtype=np.float32)
    
    # Calculate the center position
    center = size // 2
    
    # Fill the filter using the Gaussian formula
    for i in range(size):
        for j in range(size):
            x, y = i - center, j - center
            kernel[i, j] = np.exp(-(x**2 + y**2) / (2 * sigma**2))
    
    # Normalize the filter
    kernel /= 2 * np.pi * sigma**2
    kernel /= kernel.sum()
    
    return kernel

# Example usage:
gaussian_3x3 = gaussian_filter(3)
gaussian_5x5_sigma_1 = gaussian_filter(5, sigma=1)
gaussian_7x7_sigma_2 = gaussian_filter(7, sigma=2)

print("3x3 Gaussian Filter with default sigma:\n", gaussian_3x3)
print("5x5 Gaussian Filter with sigma=1:\n", gaussian_5x5_sigma_1)
print("7x7 Gaussian Filter with sigma=2:\n", gaussian_7x7_sigma_2)


3x3 Gaussian Filter with default sigma:
 [[0.01134374 0.08381951 0.01134374]
 [0.08381951 0.61934704 0.08381951]
 [0.01134374 0.08381951 0.01134374]]
5x5 Gaussian Filter with sigma=1:
 [[0.00296902 0.01330621 0.02193823 0.01330621 0.00296902]
 [0.01330621 0.0596343  0.09832034 0.0596343  0.01330621]
 [0.02193823 0.09832034 0.16210282 0.09832034 0.02193823]
 [0.01330621 0.0596343  0.09832034 0.0596343  0.01330621]
 [0.00296902 0.01330621 0.02193823 0.01330621 0.00296902]]
7x7 Gaussian Filter with sigma=2:
 [[0.00492233 0.00919612 0.01338028 0.01516185 0.01338028 0.00919612
  0.00492233]
 [0.00919612 0.01718062 0.02499766 0.02832606 0.02499766 0.01718062
  0.00919612]
 [0.01338028 0.02499766 0.03637138 0.04121417 0.03637138 0.02499766
  0.01338028]
 [0.01516185 0.02832606 0.04121417 0.04670177 0.04121417 0.02832606
  0.01516185]
 [0.01338028 0.02499766 0.03637138 0.04121417 0.03637138 0.02499766
  0.01338028]
 [0.00919612 0.01718062 0.02499766 0.02832606 0.02499766 0.01718062
  0.0091961